### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/contextily#109]
I think we try to do a 1.0 release sooner rather than later (we probably set this already a few times ;)), as it is annoying that the pip is still a pre-release, and I think the package is in good shape.

Went through our notes of last summer, and through the open issues, and apart from the PRs that I just opened, I think those ones would ideally be solved before doing the release:

- [x] decide on the API of how to pass the provider: #90 
- [ ] update documentation for new providers: #97
- [ ] update docs in general: #37

and then potentially also https://github.com/darribas/contextily/issues/82 on adding an actual sphinx documentation

**Comment by darribas** [comment]
I agree! I'm in the middle of midterm so might be tricky to squeeze hours for `contextily` until December, but maybe we can commit to a end-of-year, festive release? My main blocker was documentation and fully fleshing out and specifying the providers API. To be honest, I could do a 1.0 release with the latter and work on docs later, but it's probably a good idea to force ourselves to put both in at the same time. Bigger splash!

For the providers, I think we need to flesh out exactly how we want it to work, and this might be best done on a call. Should we set up an open one where interested folks can drop in? Alternatively, we can try and do it over at #90

**Comment by jorisvandenbossche** [comment]
I think this can be closed now?
